# Generated by Django 5.2.5 on 2025-09-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user',
            new_name='members',
        ),
    ]
